
project_id = "limxqghelamjpjihezvg"
[global.env]
SMTP_HOST = "env:SMTP_HOST"
SMTP_PORT = "env:SMTP_PORT"
SMTP_USERNAME = "env:SMTP_USERNAME"
SMTP_PASSWORD = "env:SMTP_PASSWORD"
SMTP_FROM = "env:SMTP_FROM"
