// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://limxqghelamjpjihezvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpbXhxZ2hlbGFtanBqaWhlenZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4NzUxNTAsImV4cCI6MjA1NjQ1MTE1MH0._nTXguQJ9zs1knN706y2Q4AaLwRgy75v4B4ZbTZobKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);